version: '3'
services:
    jenkins:
        image: jenkins/jenkins
        user: root
        privileged: true
        command: bash -c "apt-get update && apt-get install -y docker.io && sh && tail -f /dev/null"
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins 
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home 
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - net
networks:
    net:
